#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

if git diff-index --quiet HEAD --; then
  UNCOMMITED_CHANGES="false"
else
  UNCOMMITED_CHANGES="true"
fi

if git describe --exact-match HEAD > /dev/null 2>&1; then
  IS_RELEASE_COMMIT="true"
else
  IS_RELEASE_COMMIT="false"
fi

if $UNCOMMITED_CHANGES == "true"; then
  SUFFIX=":WIP"
elif ! $IS_RELEASE_COMMIT == "true"; then
  SUFFIX=":DEV"
else
  SUFFIX=""
fi

echo "BUILD:$(date | md5sum | rev | cut -c20- | rev):$(git rev-parse --short HEAD)$SUFFIX"
