#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

[ -d build ] || mkdir build

BUILDNO="build"
VERSION="version"

echo "Building: RIF version $VERSION, Build No $BUILDNO"

go build -ldflags "-X main.version=$VERSION -X main.buildNo=$BUILDNO" -o build/rif cmd/rif.go
go build -o build/echo-server tools/echo-server.go
