#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

cd docs
rm -rf public
hugo
cd public
git init
git remote add pages git@github.com:jonathanlloyd/rif.git
git add :/
git commit -m "Docs Build"
git push -f pages master:gh-pages
cd ../
rm -rf public
