#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

docker run -it -v $PWD:/go/src/github.com/jonathanlloyd/rif thisisjonathan/gometalinter gometalinter.v2 /go/src/github.com/jonathanlloyd/rif/./... --vendor
